language: scala
sudo: false

scala:
  - "2.12.4"
  - "2.11.11"
  - "2.10.6"

node_js:
  - "6"

script: "$TRAVIS_BUILD_DIR/travis/script/build.sh"

git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

jdk:
  - oraclejdk8

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

env:
  global:
  - secure: xxvu5mtkZsarqfATtM/HCFvsOa30jiMTnJE8CMhbNHYrjsYDff2H2ifqynafzyDa2GUuqgCHv95kzUVEnObJER0RQbWRIQ38Ej0aDlj4wlInksCgYBgaYuDXHhqehlFgccX9PGHs1KgF+fZMlgYzU3QlgYV0/qdmaxvvMDOSyzeUdJLpEUsqTx72S8o9YKPdXNx3GYeRWhNI3Sau/Ws5HvtiE+a6cFnBht+6pbcsai+nTa7Kv/nz7tENMWlhCszir4E+ZlfE+rwPa1RNlYBuAPMkBG3KU3vaFbvvlAakLioPBPAGIdG8oaJkgJbFYQ8Zys6SyUR5znJMGJiCS2cVunkanvojcbjnJ8a35WarAMrEjlR8r5wnn+agnupqI/z4G18KyNgV9v3k5Trqq4A4iwhJhgW6OO8JWo5JHoCNmnKcCbKacTztH38lLJ7ww06Qs4aOj2yLMx1w/l36LiPvV+8ZyeR8qtHV9A9dRBe5IhxSSiU8lY54GgETcLpiIAJMLZYj1w5H4Y/ylW9zOwnwasvvkwaDAWJid3/5FhQ7Zq86P+2hRe6CJVYd1Bc53yGyvAlrASlR30lKW2xAabZKYTp9Hx2QDRtmwx9IzbNxUC70Mi7d/CN1gq7GpNcBBVJfuFjQOJoEGwi2vrk/t8t26Ix1lNOGljYH6V2qqUk49ik=
  - secure: HvkKtLRjKzKmOUrGyPv9LkPCTnkojLqyQWsXZ3NfjGdB6empw4sli4BHD5Odt43he1h0Cr6Cfzh3xsdq/d3pkmcRbvVF9/xni7puFA3XeA0qngB1xKMJHTzU7DGLbL8HWxeyOrzfzIBAU54JUFRd43CAg02+jcLXF9jQYNpyrNGrlmR0HzveY9ZIxgOygkqbZEVHeFOtrK00V6il0hnSz5zOUve0DLA7zQKYzxVtrhUizOCM3zhRN8Dt+F+qy0P7K7zQLyntB5Hrfo80r9mSgw3MnEEY29Z7g5FqaoO5fzSVH1rCsyCz7SLKrrW87jPU6njg0BSM4P//nQH39dULouLDwXQczuzhCKduFRUKhWRFAFh+bjqViSERtn2iWtpkv4N9/+rneL/gsoBcWMh4lHL2r6/6WonbybRD9G6hvo6UJn9Mq95Szo1kpU7aB8RNJbr8lL1BOuAia+X5XBwI6pse0reFEf+ouvFuC+nVTmEYcGD6Hh7ZdtUyHn/kfIT9hj32inKipMWoKkAMj8SzKDN9zV8dKeK6G4sS4sk9r5N/tR7l/rndnKpiEi2N7eXkI8BvsBOJmFgU//0makLszNrEGFVxpn97eecbn2jVpz/i8S5fIAQayQtPeKM5Som0DcZmFjfw61swAwesJ9jBNnrWPvRFwugZrhAaGomdXAQ=
  - secure: jBmsA2nwnFK2Wu97m4uP6vxnts1USNXaYQWqHJc6d3WGV7TuxAEz8SyNbr/+PbweSrtN/cKMSBvW0I/rthHyfFQgGT2/qhZN6BnQoRbp9DVlaNIXJQqSGisSfCDhk1Q7KTuj4kYnXONvj0zzEiX/IiVT+zXfcV+Mtxy2ThalUe0bvoC5eskuWCZCs9fVZgv8P2tM+Y31FY9oH3jAVHWpZ4SDSlLN17GmtFf7iQuxLoz9U2qg74QNdXFGRaSPv1Bwsu8f2Faq3m7ubMUc7VzdDOvpzD5nUYa5mU96bl5XL5+7x17mHQdU6KlXPJZ9sh2yExFfTW/2RKsHy1TWVOINp1TQxcFPZsjr46N5xIUkOlftjxuppSsxfsxYYHALTfoLCL5RidaqzCyFpD7/JuEcJs607sKlz+3F8YBRT0mSpzYR1gdEZTKCc3Dc8PG6/QtfGeKRGyNx67qjuyb5/B48jqFyJGLYcsbNwRnKtU7+jeE4amjqBuWS0M4LQ5UqfV7pj03iXhyMT23tcbGgkfQOkB9iM8vOaUO9PmrLEcl//BZesw6AnXp+uH/wkSv2Vsw1V7w95yV0HSmLIqlACgrYVzx3VHrjSZFtRTY6/DpFVs6qF7nk6LxuNAf5di5eewsckMEEzXieokmQpSwFPq7oYwBJTaGCvgfLuKu78U5289M=
  - secure: I5o1jlrtewxwF0+poTmB1Utpp369y1A6P5HCli1oLzy7cWKmYaGfOdwcSrS32fX/TujHYLzHoF3yoN51aGaMMCQGEEukuEReRe6toIPsAqhJOql+ojEBAxJQduYwFRIckSvoIF6PXuOeRiGrl18ON0UVd2r/d/byIHAgD3aBEqaP2ldTRUtvuE76WsolzmmsHdV693S8L7Z/4HWdqU7Vqbx1fTvzteKSKQn7fymNs1JIG0LkZpz6uH6OwVaZjImjsPmvr9vLoUGHhFMUEiYaERg4Omc42h0IDX0ZxqlPLsbicvCeijewffH+9DWfRhddaqO1gbWpE6NukZmqH6KP2duVquAtEjLpnCs5MAcZODF7SciOE5GZbw7nSngCA2w0f0wx/GoErQoUGyH7HdKoS/KYoOD5ky5MZmVeBQTfRpQwHt3UMbe1RSGxacENWac5dJKooTOpabcP/VQ2vAMzwSe69wsWzdqBt67G57FtPer2edaVIjLa5tKCFDyL0UiL4Zd6jKNH3f++N16CIhmm/1Gz8PVTIBHvMTFZI2KXb1+KMCTg1XAXrQRS/JDQYUSZqv1Yx7FKbKo3rT3ldqG3hfEk2E6Q+mOHk9LV+6e2RMxPcTFaSMCxYLBD6sU8nx8Qrw4CX5lnWxG25f5q54hLiBE2SzywSrtChl44L54fXuw=
